quarkus.http.port=5004
# Database configuration for Quarkus application
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${DB_NAME}
# Quinoa
quarkus.quinoa.dev-server.enabled=true
quarkus.quinoa.package-manager=pnpm
quarkus.quinoa.ui-dir=../frontend
quarkus.quinoa.build-dir=ui
quarkus.quinoa.ui-root-path=/home
quarkus.quinoa.enable-spa-routing=true
