quarkus.http.port=5004
# Quinoa
quarkus.quinoa.dev-server.enabled=true
quarkus.quinoa.package-manager=pnpm
quarkus.quinoa.ui-dir=frontend
quarkus.quinoa.build-dir=ui
quarkus.quinoa.ui-root-path=/home
quarkus.quinoa.enable-spa-routing=true
