quarkus.http.port=5004
# Database configuration for Quarkus application
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_HOST}
# Liquibase configuration
#quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog.xml
# Quinoa
quarkus.quinoa.dev-server.enabled=true
quarkus.quinoa.package-manager=pnpm
quarkus.quinoa.ui-dir=../frontend
quarkus.quinoa.build-dir=ui
quarkus.quinoa.ui-root-path=/home
quarkus.quinoa.enable-spa-routing=true
# Authentication and JWT
mp.jwt.verify.issuer={APP_JWT_ISSUER}
mp.jwt.verify.publickey.location=classpath:keys/public.pem
mp.jwt.verify.publickey.algorithm=RS256
smallrye.jwt.sign.key.location=classpath:keys/private.pem
smallrye.jwt.sign.algorithm=RS256